name: Rubocop

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  ruby_workflow_checkout:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.3']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Rubocop
      run: bundle exec rubocop
